#!/usr/bin/env node

const fs = require('fs')

// read data from stdin
var data = JSON.parse(fs.readFileSync(0, 'utf-8'))

// for each layer update each feature with the _layer property
data.layers.forEach(layer =>
  layer.features.forEach(f => f.properties._layer = layer._storage.name)
)

// now collect the features of all layers into a single array
let features = data.layers.reduce(
  (features, layer) => features.concat(layer.features),
  []
)

// create final GeoJSON structure
data = {type:'FeatureCollection', features}

// print
console.log(JSON.stringify(data, null, '    '))
